Repository eKhattak/hackshare, pull requests merged in 2020-07, with the labels that each got.

#10 Connect to Schema
  server/Helper/db.js
  server/Model/achievement.js
  server/Model/challenge.js
  server/Model/endorsement.js
  server/Model/expertise.js
  server/Model/index.js
  server/Model/learning.js
  server/Model/meeting.js
  server/Model/task.js
  server/Model/user.js
  server/README.md
  server/Routes/user.js
  server/app.js
  server/package-lock.json
  server/package.json
Labels: backend

#9 Add basic auth ground work
  client/.env.example
  client/.gitignore
  client/package.json
  client/src/App.js
  client/src/index.js
  client/yarn.lock
  server/.env.example
  server/Helper/db.js
  server/README.md
  server/Routes/user.js
  server/app.js
  server/package.json
Labels: backend

#12 Rashika/11
  client/package.json
  client/src/.env.example
  client/src/App.css
  client/src/App.js
  client/src/Pages/Experts.js
  client/src/Pages/Landing.js
  client/src/Pages/Learners.js
  client/src/Pages/Profile.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/yarn.lock
Labels: frontend

#14 Update Readme
  README.md
Labels: documentation

#26 Learnings API
  server/Controller/learning.js
  server/Model/index.js
  server/Routes/index.js
  server/Routes/learning.js
  server/app.js
Labels: backend

#23 Expertise API
  server/Controller/expertise.js
  server/Routes/expertise.js
  server/Routes/index.js
  server/app.js
  server/package-lock.json
  server/package.json
Labels: backend

#24 Restructure and protect routes
  client/public/index.html
  client/src/.env.example
  client/src/App.js
  client/src/Pages/Experts.js
  client/src/Pages/Landing.js
  client/src/Pages/Learners.js
  client/src/Pages/Profile.js
  client/src/index.js
  client/src/layout/Footer/index.js
  client/src/layout/Footer/index.module.css
  client/src/layout/Header/index.js
  client/src/layout/Header/index.module.css
  client/src/pages/Experts/index.js
  client/src/pages/Experts/index.module.css
  client/src/pages/Fallback/index.js
  client/src/pages/Fallback/index.module.css
  client/src/pages/Landing/index.js
  client/src/pages/Landing/index.module.css
  client/src/pages/Learners/index.js
  client/src/pages/Learners/index.module.css
  client/src/pages/Profile/index.js
  client/src/pages/Profile/index.module.css
  client/src/router.js
Labels: enhancement, frontend, high priority

#30 Add user api
  client/src/App.js
  server/Controller/user.js
  server/Routes/user.js
  server/app.js
  server/controller/expertise.js
  server/controller/learning.js
  server/controller/user.js
  server/helper/db.js
  server/model/achievement.js
  server/model/challenge.js
  server/model/endorsement.js
  server/model/expertise.js
  server/model/freeSlot.js
  server/model/index.js
  server/model/learning.js
  server/model/meeting.js
  server/model/task.js
  server/model/user.js
  server/package.json
  server/routes/expertise.js
  server/routes/index.js
  server/routes/learning.js
  server/routes/user.js
  server/yarn.lock
Labels: backend

#33 Add eslint and code styler
  client/.eslintrc.js
  client/.gitignore
  client/package.json
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.js
  client/src/layout/Footer/index.js
  client/src/layout/Footer/index.module.css
  client/src/layout/Header/index.js
  client/src/layout/Header/index.module.css
  client/src/pages/Experts/index.js
  client/src/pages/Fallback/index.js
  client/src/pages/Landing/index.js
  client/src/pages/Learners/index.js
  client/src/pages/Profile/index.js
  client/src/router.js
  client/src/serviceWorker.js
  client/src/setupTests.js
  client/yarn.lock
Labels: enhancement, frontend

#36 Nav Bar Styling
  client/package.json
  client/public/Landing-Shared.svg
  client/public/github.svg
  client/src/App.css
  client/src/assets/Logo.svg
  client/src/components/ProfileMenu/index.js
  client/src/components/ProfileMenu/index.module.css
  client/src/layout/Header/index.js
  client/src/layout/Header/index.module.css
  client/src/pages/Profile/index.js
  client/yarn.lock
Labels: design, enhancement, frontend, high priority

#37 Landing page content and style
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/assets/Logo.svg
  client/src/assets/illustrations/Landing-Shared.svg
  client/src/assets/illustrations/Profile-Skills.svg
  client/src/assets/illustrations/Welcoming.svg
  client/src/layout/Footer/index.js
  client/src/layout/Footer/index.module.css
  client/src/layout/Header/index.js
  client/src/pages/Landing/index.js
  client/src/pages/Landing/index.module.css
  client/src/pages/Profile/index.js
Labels: design, enhancement, frontend, high priority

#58 Update profile with learnings
  client/src/pages/Profile/index.js
Labels: enhancement, frontend
